name: ave_memoria
description: "Diploma"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.2
  equatable: ^2.0.5
  flutter_svg_provider: ^1.0.3
  cached_network_image: ^3.3.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.9
  connectivity_plus: ^5.0.2
  flutter_localizations:
    sdk: flutter
  supabase_flutter: ^1.10.3
  flutter_native_splash: ^2.3.4
  page_view_indicators: ^2.0.0
  bloc_concurrency: ^0.2.0
  go_router: ^6.0.1
  font_awesome_flutter: ^10.2.1
  get_it: ^7.2.0
  dio: ^4.0.6
  sizer: ^2.0.15
  internet_connection_checker: ^1.0.0+1
  google_sign_in: ^6.1.6
  url_launcher: ^6.2.1
  intl: ^0.18.1
  image_picker: ^0.8.4
  smooth_page_indicator: ^1.1.0
  awesome_dialog: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/PoppinsExtraBold.ttf
          weight: 800
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsLight.ttf
          weight: 300
        - asset: assets/fonts/PoppinsBold.ttf
          weight: 700