name: ave_memoria
description: "Diploma"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.5
  shared_preferences: ^2.2.3
  equatable: ^2.0.5
  flutter_svg_provider: ^1.0.7
  cached_network_image: ^3.3.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  connectivity_plus: ^5.0.1
  flutter_localizations:
    sdk: flutter
  supabase_flutter: ^2.5.1
  flutter_native_splash: ^2.4.0
  page_view_indicators: ^2.0.0
  bloc_concurrency: ^0.2.5
  go_router: ^14.0.0
  font_awesome_flutter: ^10.7.0
  get_it: ^7.7.0
  dio: ^5.4.3+1
  sizer: ^2.0.15
  internet_connection_checker: ^1.0.0+1
  google_sign_in: ^6.2.1
  url_launcher: ^6.2.6
  intl: ^0.18.0
  image_picker: ^1.1.0
  smooth_page_indicator: ^1.1.0
  awesome_dialog: ^3.2.0
  flip_card: ^0.7.0
  flutter_rating_bar: ^4.0.1
  percent_indicator: ^4.2.3
  flutter_offline: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/PoppinsExtraBold.ttf
          weight: 800
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsLight.ttf
          weight: 300
        - asset: assets/fonts/PoppinsBold.ttf
          weight: 700